spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:database/changelog/db.changelog-master.yaml

jwt:
  secret: 'VSVGqRQYZmVTy426JEnUiAmgzmL4RJmSywqqRPX90Xs='
  lifetime: '1h'

server:
  port: 8080